# Generated by Django 3.0.8 on 2020-07-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default=True, max_length=254, unique=True)),
                ('designation', models.CharField(default=None, max_length=50)),
                ('date_Of_birth', models.DateField(default=None)),
                ('password', models.CharField(default=True, max_length=100)),
                ('contact', models.CharField(default=True, max_length=20)),
            ],
        ),
    ]
